package com.bootcamp.customerregistration.customerservice.customerdetails.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-16T15:57:25.787-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://service.customerdetails.customerservice.com/", name = "SoapServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://service.customerdetails.customerservice.com/", className = "com.bootcamp.customerregistration.customerservice.customerdetails.service.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://service.customerdetails.customerservice.com/", className = "com.bootcamp.customerregistration.customerservice.customerdetails.service.GetServicePlansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bootcamp.customerregistration.customerservice.customerdetails.service.ServicePlan> getServicePlans();
}
