
package com.customerservice.customerdetails.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapServiceImpl", targetNamespace = "http://service.customerdetails.customerservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.customerservice.customerdetails.service.ServicePlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://service.customerdetails.customerservice.com/", className = "com.customerservice.customerdetails.service.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://service.customerdetails.customerservice.com/", className = "com.customerservice.customerdetails.service.GetServicePlansResponse")
    public List<ServicePlan> getServicePlans();

}
